stages:
  - build
  - test
  - release

default:
  image: python:latest

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip

build:
  stage: build
  script:
    - pip install pep517 #twine
    - python -m pep517.build --source --binary .
  artifacts:
    paths:
      - dist/*.whl

test:
  stage: test
  parallel:
    matrix:
      - PY: ["3.7", "3.8", "3.9-rc"]
  image: python:$PY
  script:
    - pip install $(ls dist/*.whl)[dev]
    - pytest --cov=src/ --cov-report=term-missing
  coverage: '/^TOTAL.*\s+(\d+\%)\s*$/'

release:
  stage: release
  only:
    - tags
  script:
    - echo "Uploading: $(ls dist/)"
