stages:
  - build
  - test
  - post-test
  - pre-release
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: python:latest
  before_script:
    - pip install nox
  cache:
    paths:
      - .cache/pip

build:
  stage: build
  script:
    - nox --forcecolor -s build
  artifacts:
    paths:
      - dist/

lint:
  stage: test
  script:
    - nox --forcecolor -s lint

mypy:
  stage: test
  script:
    - nox --forcecolor -s mypy

test:
  stage: test
  parallel:
    matrix:
      - PY: ["3.7", "3.8", "3.9-rc"]
        PKG_FORMAT: ["src", "whl"]
  image: python:$PY
  script:
    # "%%-*" strips the longest possible match of "-*" from the right:
    - >-
      nox --forcecolor -s "test-${PY%%-*}($PKG_FORMAT)" --
      --junit-xml=report-${PY%%-*}-${PKG_FORMAT}.xml
      tests
  artifacts:
    paths:
      - ".coverage"
      - ".coverage.*"
    reports:
      junit: "report-*.xml"

test-coverage:
  stage: post-test
  script:
    - nox --forcecolor -s coverage-report
  coverage: '/^TOTAL.*\s+(\d+\%)\s*$/'

release-check:
  stage: pre-release
  only:
    - tags
  script:
    - pip install twine
    - twine check dist/*
    - twine upload --repository-url https://test.pypi.org/legacy/ --username __token__ --password $(cat $TEST_PYPI_TOKEN) dist/*

release:
  stage: release
  only:
    - tags
  when: manual
  script:
    - pip install twine
    - twine upload --repository-url https://upload.pypi.org/legacy/ --username __token__ --password $(cat $UPLOAD_PYPI_TOKEN) dist/*
