stages:
  - build
  - test
  - release-check
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: python:latest
  cache:
    paths:
      - .cache/pip

build:
  stage: build
  script:
    - pip install pep517 #twine
    - python -m pep517.build --source --binary .
  artifacts:
    paths:
      - dist/

test-builds:
  stage: test
  parallel:
    matrix:
      - PY: ["3.8", "3.9-rc"]
        PKG_FORMAT: ["tar.gz", "whl"]
  image: python:$PY
  script:
    - pip install $(ls dist/*.$PKG_FORMAT)[dev]
    - pytest --cov=src/ --cov-report=term-missing

test-coverage:
  stage: test
  script:
    - pip install -e.[dev]
    - pytest --cov=src/ --cov-report=term-missing
  coverage: '/^TOTAL.*\s+(\d+\%)\s*$/'

release-check:
  stage: release
  only:
    - tags
  script:
    - pip install twine
    - twine check dist/*
    - twine --repository-url https://test.pypi.org/legacy/ --username __token__ --password $(cat $PYPI_TOKEN)

release:
  stage: release
  only:
    - tags
  when: manual
  script:
    - pip install twine
    - twine --repository-url https://upload.pypi.org/legacy/ --username __token__ --password $(cat $PYPI_TOKEN)
